### ISSUE TITLE
`thread 'main' panicked at 'Failed to spawn process: Error(Msg("Unexpected process status: Signaled(7771, SIGTERM, false)")`

### ISSUE THREAD

**Issue by jgraham** [luser/tracetree#3]
```
thread 'main' panicked at 'Failed to spawn process: Error(Msg("Unexpected process status: Signaled(7771, SIGTERM, false)"), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x55fda50ef0fc - backtrace::backtrace::trace::h58bdbc4722aadbf4
   1:     0x55fda50ef242 - backtrace::capture::Backtrace::new::hde1afc496271e12d
   2:     0x55fda50ae0a6 - error_chain::make_backtrace::hb3affedfab149f41
   3:     0x55fda50ae158 - <error_chain::State as core::default::Default>::default::h0287c2899b6ba4bd
   4:     0x55fda50acbab - <tracetree::errors::Error as core::convert::From<collections::string::String>>::from::hd80ab8e5123d5b17
   5:     0x55fda501eaea - tracetree::ProcessTree::spawn::h318ee82efe85e77e
   6:     0x55fda5020160 - tracetree::main::h0c4d1b8d40bb9fd3
   7:     0x55fda511349a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   8:     0x55fda510ccf8 - std::panicking::try<(),closure>
                        at /checkout/src/libstd/panicking.rs:433
                         - std::panic::catch_unwind<closure,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::rt::lang_start
                        at /checkout/src/libstd/rt.rs:59
   9:     0x7fd72b3863f0 - __libc_start_main
  10:     0x55fda50175c9 - _start
  11:                0x0 - <unknown>) })', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: tracetree::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: _start
```

This was `tracetree ./mach wpt testing/web-platform/tests/compat` although on a branch.

**Comment by luser** [comment]
Oh huh, I failed to handle this properly. This happens if a process is terminated by a signal.
